const USER = "USER"
const CONSULTANT = "CONSULTANT"
const EMPLOYER = "EMPLOYER"
const REPRESENTATIVE = "REPRESENTATIVE"
const MANAGER = "MANAGER"
const ADMIN = "ADMIN"

module.exports = {
    USER, CONSULTANT, EMPLOYER, REPRESENTATIVE, MANAGER, ADMIN
}